version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: GoKapture
      MYSQL_USER: GoKaptureUser
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql


  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql